// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3620.FRC3620_Killer_Rabbit;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveSubsystemLeftFront;
    public static SpeedController driveSubsystemLeftRear;
    public static SpeedController driveSubsystemRightFront;
    public static SpeedController driveSubsystemRightRear;
    public static RobotDrive driveSubsystemRobotDrive41;
    public static Encoder driveSubsystemLeftDriveEncoder;
    public static Encoder driveSubsystemRightDriveEncoder;
    public static CANTalon shooterSubsystemShooterCANTalon1;
    public static SpeedController shooterSubsystemShooterPositionTalon;
    public static CANTalon armSubsystemArmCANTalon;
    public static AnalogInput intakeSubsystemBallSensorAnalogInput;
    public static Encoder intakeSubsystemIntakeRollerEncoder;
    public static SpeedController intakeSubsystemIntakeRollerTalonFront;
    public static SpeedController intakeSubsystemIntakeRollerTalonBack;
    public static AnalogInput dummySubsystemAnalogInput1;
    public static DigitalInput dummySubsystemDigitalInput0;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public static void init() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSubsystemLeftFront = new Talon(1);
        LiveWindow.addActuator("DriveSubsystem", "Left Front", (Talon) driveSubsystemLeftFront);
        
        driveSubsystemLeftRear = new Talon(2);
        LiveWindow.addActuator("DriveSubsystem", "Left Rear", (Talon) driveSubsystemLeftRear);
        
        driveSubsystemRightFront = new Talon(3);
        LiveWindow.addActuator("DriveSubsystem", "Right Front", (Talon) driveSubsystemRightFront);
        
        driveSubsystemRightRear = new Talon(4);
        LiveWindow.addActuator("DriveSubsystem", "Right Rear", (Talon) driveSubsystemRightRear);
        
        driveSubsystemRobotDrive41 = new RobotDrive(driveSubsystemLeftFront, driveSubsystemLeftRear,
              driveSubsystemRightFront, driveSubsystemRightRear);
        
        driveSubsystemRobotDrive41.setSafetyEnabled(true);
        driveSubsystemRobotDrive41.setExpiration(0.1);
        driveSubsystemRobotDrive41.setSensitivity(0.5);
        driveSubsystemRobotDrive41.setMaxOutput(1.0);
        driveSubsystemRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        driveSubsystemRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        driveSubsystemRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveSubsystemRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        driveSubsystemLeftDriveEncoder = new Encoder(1, 2, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveSubsystem", "LeftDriveEncoder", driveSubsystemLeftDriveEncoder);
        driveSubsystemLeftDriveEncoder.setDistancePerPulse(1.0);
        driveSubsystemLeftDriveEncoder.setPIDSourceType(PIDSourceType.kRate);
        driveSubsystemRightDriveEncoder = new Encoder(3, 4, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveSubsystem", "RightDriveEncoder", driveSubsystemRightDriveEncoder);
        driveSubsystemRightDriveEncoder.setDistancePerPulse(1.0);
        driveSubsystemRightDriveEncoder.setPIDSourceType(PIDSourceType.kRate);
        shooterSubsystemShooterCANTalon1 = new CANTalon(2);
        LiveWindow.addActuator("ShooterSubsystem", "ShooterCANTalon1", shooterSubsystemShooterCANTalon1);
        
        shooterSubsystemShooterPositionTalon = new Talon(5);
        LiveWindow.addActuator("ShooterSubsystem", "ShooterPositionTalon", (Talon) shooterSubsystemShooterPositionTalon);
        
        armSubsystemArmCANTalon = new CANTalon(1);
        LiveWindow.addActuator("ArmSubsystem", "ArmCANTalon", armSubsystemArmCANTalon);
        
        intakeSubsystemBallSensorAnalogInput = new AnalogInput(0);
        LiveWindow.addSensor("IntakeSubsystem", "Ball Sensor Analog Input", intakeSubsystemBallSensorAnalogInput);
        
        intakeSubsystemIntakeRollerEncoder = new Encoder(6, 7, false, EncodingType.k4X);
        LiveWindow.addSensor("IntakeSubsystem", "Intake RollerEncoder", intakeSubsystemIntakeRollerEncoder);
        intakeSubsystemIntakeRollerEncoder.setDistancePerPulse(1.0);
        intakeSubsystemIntakeRollerEncoder.setPIDSourceType(PIDSourceType.kRate);
        intakeSubsystemIntakeRollerTalonFront = new Talon(6);
        LiveWindow.addActuator("IntakeSubsystem", "IntakeRollerTalonFront", (Talon) intakeSubsystemIntakeRollerTalonFront);
        
        intakeSubsystemIntakeRollerTalonBack = new Talon(7);
        LiveWindow.addActuator("IntakeSubsystem", "IntakeRollerTalonBack", (Talon) intakeSubsystemIntakeRollerTalonBack);
        
        dummySubsystemAnalogInput1 = new AnalogInput(1);
        LiveWindow.addSensor("DummySubsystem", "Analog Input 1", dummySubsystemAnalogInput1);
        
        dummySubsystemDigitalInput0 = new DigitalInput(0);
        LiveWindow.addSensor("DummySubsystem", "Digital Input 0", dummySubsystemDigitalInput0);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	}
}
