// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3620.FRC3620_Killer_Rabbit;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveSubsystemLeftFront;
    public static SpeedController driveSubsystemLeftRear;
    public static SpeedController driveSubsystemRightFront;
    public static SpeedController driveSubsystemRightRear;
    public static RobotDrive driveSubsystemRobotDrive41;
    public static CANTalon shooterSubsystemShooterCANTalon1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public static void init() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSubsystemLeftFront = new Talon(1);
        LiveWindow.addActuator("DriveSubsystem", "Left Front", (Talon) driveSubsystemLeftFront);
        
        driveSubsystemLeftRear = new Talon(2);
        LiveWindow.addActuator("DriveSubsystem", "Left Rear", (Talon) driveSubsystemLeftRear);
        
        driveSubsystemRightFront = new Talon(3);
        LiveWindow.addActuator("DriveSubsystem", "Right Front", (Talon) driveSubsystemRightFront);
        
        driveSubsystemRightRear = new Talon(4);
        LiveWindow.addActuator("DriveSubsystem", "Right Rear", (Talon) driveSubsystemRightRear);
        
        driveSubsystemRobotDrive41 = new RobotDrive(driveSubsystemLeftFront, driveSubsystemLeftRear,
              driveSubsystemRightFront, driveSubsystemRightRear);
        
        driveSubsystemRobotDrive41.setSafetyEnabled(true);
        driveSubsystemRobotDrive41.setExpiration(0.1);
        driveSubsystemRobotDrive41.setSensitivity(0.5);
        driveSubsystemRobotDrive41.setMaxOutput(1.0);
        driveSubsystemRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        driveSubsystemRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        shooterSubsystemShooterCANTalon1 = new CANTalon(1);
        LiveWindow.addActuator("ShooterSubsystem", "ShooterCANTalon1", shooterSubsystemShooterCANTalon1);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	}
}
