// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.FRC3620_Killer_Rabbit.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3620.FRC3620_Killer_Rabbit.Robot;

/**
 *
 */
public class OuttakeCommand extends Command {

    public OuttakeCommand() {
    	requires(Robot.intakeSubsystem);
   
    }

    // Called just before this Command runs the first time
  
    Timer timer = new Timer ();
    protected void initialize() {
    	Robot.intakeSubsystem.dumpOut();
    		timer.reset();
    		timer.start();
    	if (Robot.armSubsystem.isArmUp())
    		Robot.intakeSubsystem.intakeStop();
    	
    }
    

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.intakeSubsystem.dumpOut();
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	// if button is down, we defnitely are not finished
    	if (Robot.oi.outtake.get()) return false;
    	return timer.hasPeriodPassed(1);
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.intakeSubsystem.intakeStop();
    	
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end ();
    }
}
