// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.FRC3620_Killer_Rabbit.subsystems;

import org.usfirst.frc3620.FRC3620_Killer_Rabbit.Robot;
import org.usfirst.frc3620.FRC3620_Killer_Rabbit.RobotMap;
import org.usfirst.frc3620.FRC3620_Killer_Rabbit.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CANTalon.FeedbackDevice;
import edu.wpi.first.wpilibj.CANTalon.TalonControlMode;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class ArmSubsystem extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon armCANTalon = RobotMap.armSubsystemArmCANTalon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public ArmSubsystem() {
		super();
		// TODO Auto-generated constructor stub
		armCANTalon.changeControlMode(TalonControlMode.Position);
		weAreInManualMode = false;
    	armCANTalon.setFeedbackDevice(FeedbackDevice.CtreMagEncoder_Absolute);
    	armCANTalon.setPID(0.1, .00001, 0.01);
	}
    
    boolean weAreInManualMode = false;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
  
    public void raiseArm()
    {
		armCANTalon.changeControlMode(TalonControlMode.Position);
		weAreInManualMode = true;
    	armCANTalon.setSetpoint(1);
    	System.out.println("setpoint 1");
    }
    
    public void lowerArm()
    {
		armCANTalon.changeControlMode(TalonControlMode.Position);
		weAreInManualMode = true;
    	armCANTalon.setSetpoint(0);
    	System.out.println("setpoint 0");
    }
    
    public void goIntoAutomaticMode() {
    	if (weAreInManualMode) {
    		armCANTalon.changeControlMode(TalonControlMode.Position);
    		armCANTalon.setSetpoint(armCANTalon.getEncPosition());
    		weAreInManualMode = false;
    	}
    }
    
    public void setManualPower(double power)
    {
    	if (!weAreInManualMode) {
    		// TODO double check this - Voltage or VBus?
    		armCANTalon.changeControlMode(TalonControlMode.Voltage);
    		weAreInManualMode = true;
    		
    	}
    	armCANTalon.set(power);
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new ArmManualCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

