// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.FRC3620_Killer_Rabbit.subsystems;

import org.usfirst.frc3620.FRC3620_Killer_Rabbit.RobotMap;

import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.Relay.Value;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class LightSubsystem extends Subsystem {
    private final Relay spike0 = RobotMap.lightSubsystemSpike0;
    private final Relay spike1 = RobotMap.lightSubsystemSpike1;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    private boolean headLight = false;
    private boolean red = false;
    private boolean blue = false;
    private boolean green = false;

    public void initDefaultCommand() {
    }
    
    public void setHeadlight (boolean b) {
    	headLight = b;
    	hitRelays();
    }
    
    public void setRed (boolean b) {
    	red = b;
    	hitRelays();
    }
    
    public void setGreen (boolean b) {
    	green = b;
    	hitRelays();
    }
    
    public void setBlue (boolean b) {
    	blue = b;
    	hitRelays();
    }
    
    public void setColor (int color) {
        red = (color & 0xff0000) > 0x800000;
        green = (color & 0x00ff00) > 0x008000;
        blue = (color & 0x0000ff) > 0x000080;
        hitRelays();
    }

    void hitRelays() {
    	Relay.Value s0 = Value.kOff;
    	if (red) {
    		if (green) {
    			s0 = Value.kOn;
    		} else {
    			// red only
    			s0 = Value.kForward;
    		}
    	} else {
    		if (green) {
			  s0 = Value.kReverse;
    		}
    	}
    	spike0.set(s0);
    	
    	Relay.Value s1 = Value.kOff;
    	if (blue) {
    		if (headLight) {
    			s1 = Value.kOn;
    		} else {
    			// blue only
    			s1 = Value.kForward;
    		}
    	} else {
    		if (headLight) {
    			// headlight only
			    s1 = Value.kReverse;
    		}
    	}
    	spike1.set(s1);
    }
    
}

