// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.FRC3620_Killer_Rabbit.subsystems;

import org.usfirst.frc3620.FRC3620_Killer_Rabbit.RobotMap;
import org.usfirst.frc3620.FRC3620_Killer_Rabbit.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class ShooterSubsystem extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    public ShooterSubsystem() {
		super();
		
		shooterCANTalon3.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
		//shooterCANTalon3.set(shooterCANTalon2.getDeviceID());
		
		// TODO Auto-generated constructor stub
	}

    private final CANTalon shooterCANTalon2 = RobotMap.shooterSubsystemShooterCANTalon2;
    private final CANTalon shooterCANTalon3 = RobotMap.shooterSubsystemShooterCANTalon3;
    private final SpeedController shooterPositionTalon = RobotMap.shooterSubsystemShooterPositionTalon;
    
    boolean shooterWasRunning;
    
    Timer timer = new Timer();
    
    /*public void ShootOut()
    {
    	shooterCANTalon2.set(1);
    }

    public void ShootOutReverse()
    {
    	shooterCANTalon2.set(-1);
    }
    
    public void ShootOutStop()
    {
    	shooterCANTalon2.set(0)
    }*/
    public void setPower(double power)
    {
    	shooterCANTalon2.set(power);
    	shooterCANTalon3.set(power);
		if (power == 0) 
		{
			//Motors are off here.
			if (shooterWasRunning)
			{
				//We just turned the shooter off.

		    	timer.stop();
				timer.reset();
			}
		}
		else
		{
			//Motors are on here.
			if (!shooterWasRunning)
			{				
				//We just turned the shooter on.
				timer.start();
			}
		}
    }
    
    public void setUpTalons()
    {
    	shooterCANTalon3.changeControlMode(CANTalon.TalonControlMode.Follower);
		shooterCANTalon3.set(shooterCANTalon2.getDeviceID());
    }
    
    public boolean checkShooter()
    {
		return timer.get() > 3;
    }
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

