// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.FRC3620_Killer_Rabbit.subsystems;



import org.slf4j.Logger;
import org.usfirst.frc3620.FRC3620_Killer_Rabbit.Robot;
import org.usfirst.frc3620.FRC3620_Killer_Rabbit.RobotMap;
import org.usfirst.frc3620.FRC3620_Killer_Rabbit.commands.*;
import org.usfirst.frc3620.logger.EventLogging;
import org.usfirst.frc3620.logger.EventLogging.Level;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.AnalogTrigger;
import edu.wpi.first.wpilibj.AnalogTriggerOutput.AnalogTriggerType;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Counter;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.InterruptHandlerFunction;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class ShooterSubsystem extends Subsystem {
	Logger logger = EventLogging.getLogger(getClass(), Level.INFO);

	private final CANTalon shooterCANTalon2 = RobotMap.shooterSubsystemShooterCANTalon2;
    private final CANTalon shooterCANTalon3 = RobotMap.shooterSubsystemShooterCANTalon3;
    private final SpeedController shooterPositionTalon = RobotMap.shooterSubsystemShooterPositionTalon;
    private final AnalogInput shooterTiltSensor  = RobotMap.shooterSubsystemTiltSensor;
    private final DigitalInput shooterHomeDigitalInput = RobotMap.shooterSubsystemHomeDigitalInput;
    
    public AnalogTrigger analogTrigger;
    
    Counter tiltCounter;
    boolean shooterWasRunning;
    boolean shooterWasGoingUp;
    boolean counterIsValid;
   
    double gearCounts;
    int tiltCounterBase = 0;
    
    Timer timer = new Timer();
    
	
    public ShooterSubsystem() {
		super();
		
		analogTrigger = new AnalogTrigger(shooterTiltSensor);
		analogTrigger.setLimitsVoltage(3.1, 3.3);
		analogTrigger.setAveraged(true);
		tiltCounter = new Counter();
		tiltCounter.setUpSource(analogTrigger, AnalogTriggerType.kRisingPulse);
		tiltCounter.clearDownSource();
		shooterWasGoingUp = true;
		counterIsValid = false;
		
		shooterCANTalon2.changeControlMode(CANTalon.TalonControlMode.Voltage);
		shooterCANTalon2.setVoltageCompensationRampRate(24.0);
		shooterCANTalon2.enableBrakeMode(false);
		
		shooterCANTalon3.changeControlMode(CANTalon.TalonControlMode.Voltage);
		shooterCANTalon3.setVoltageCompensationRampRate(24.0);
		shooterCANTalon3.enableBrakeMode(false);
		
		//shooterCANTalon3.set(shooterCANTalon2.getDeviceID());
		
		// TODO Auto-generated constructor stub
		
	    if(isShooterAtHome())
	    	{
	    		logger.info("Shooter Position at home");
	    		counterIsValid = true;
	    		tiltCounter.reset();
	    		tiltCounterBase = 0;
	    	}
	    	
				//Arm not home, set for homing.
				RobotMap.shooterSubsystemHomeDigitalInput.requestInterrupts(new MyHandler());
				RobotMap.shooterSubsystemHomeDigitalInput.setUpSourceEdge(false, true);
				RobotMap.shooterSubsystemHomeDigitalInput.enableInterrupts();	
		
	    
		
	    	gearCounts = edu.wpi.first.wpilibj.Preferences.getInstance().getDouble("gearCounts", 14);
	    	logger.info("Gear Counts: {}", gearCounts);
	}
    
    class MyHandler extends InterruptHandlerFunction<Void> {

		@Override
		public void interruptFired(int interruptAssertedMask, Void param) {
			logger.info("Interrupt happened.");
			//if (!isCounterIsValid()) {
			if (!shooterWasGoingUp){
	    		counterIsValid = true;
	    		//tiltCounter.reset();
	    		//tiltCounterBase = 0;
				logger.info("Resetting Counter");
				//RobotMap.shooterSubsystemHomeDigitalInput.disableInterrupts();
			}
			else{
				logger.info("Ignoring interrupt, shooter on the way up");
			}
		}
    	
    }

    public boolean isCounterIsValid() {
		return counterIsValid;
	}

    /*public void ShootOut()
    {
    	shooterCANTalon2.set(1);
    }

    public void ShootOutReverse()
    {
    	shooterCANTalon2.set(-1);
    }
    
    public void ShootOutStop()
    {
    	shooterCANTalon2.set(0)
    }*/
    
    public void setShooterVoltage(double voltage)
    {
    	
    	shooterCANTalon2.set(voltage);
    	shooterCANTalon3.set(voltage);
		if (voltage == 0) 
		{
			//Motors are off here.
			if (shooterWasRunning)
			{
				//We just turned the shooter off.
				logger.info("Shooter just stopped running");
		    	timer.stop();
				timer.reset();
			}
			shooterWasRunning=false;
		}
		else
		{
			//Motors are on here.
			if (!shooterWasRunning)
			{				
				//We just turned the shooter on.
				logger.info("Shooter just started running");
				timer.start();
			}
			shooterWasRunning=true;
		}
    }
    
    public void setUpTalons()
    {
    	shooterCANTalon3.changeControlMode(CANTalon.TalonControlMode.Follower);
		shooterCANTalon3.set(shooterCANTalon2.getDeviceID());
    }
    
    public boolean checkShooter()
    {
		return timer.get() > 1;
    }
    
    public void moveShooterPositionUp(double power)
    {
    	setMoveTilt(power);
    }
    
    public void moveShooterPositionDown(double power)
    {
    	setMoveTilt(-power);

    }
    
    public void stopShooterPositionTalon()
    {
    	shooterPositionTalon.set(0);
    }
    
    public int getCounterValue()
    {
    	return tiltCounter.get();
    }
    
    public int getTiltCounter()
    {
    	
    	return tiltCounterBase + tiltCounter.get();
    }
 
 	public double getTiltVeds()
 	{
 			return getTiltCounter() * (gearCounts/14);
 		
 	} 
    
    public void setMoveTilt(double power)
    {
    	if(power>0)
    	{ 
    		if(!shooterWasGoingUp)
    		{
    			logger.info("Changing shooter counter to up, counter " + tiltCounter.get());
    			logger.info("Manual counter " + getTiltCounter());

    			tiltCounterBase = getTiltCounter();
    			
    			tiltCounter.setUpSource(analogTrigger, AnalogTriggerType.kRisingPulse);
    			tiltCounter.clearDownSource();
    		
    			
    			logger.info("Changing shooter counter to up, counter " + tiltCounter.get());
    			logger.info("Manual counter " + getTiltCounter());
    		}
    		shooterWasGoingUp = true;
    	}
    	else if(power<0)
    	{
    		if(shooterWasGoingUp)
    			
    		{
    			logger.info("Changing shooter counter to down, counter " + tiltCounter.get());
    			logger.info("Manual counter " + getTiltCounter());
    			
    			tiltCounterBase = getTiltCounter();
    			
    			tiltCounter.setDownSource(analogTrigger, AnalogTriggerType.kRisingPulse);
    			tiltCounter.clearUpSource();
    			
    			logger.info("Changing shooter counter to down, counter " + tiltCounter.get());
    			logger.info("Manual counter " + getTiltCounter());
    		}
    		shooterWasGoingUp = false;
    	}
    	
    	if (power < 0 && isShooterAtHome()) {
    		// don't go past home
    		//power = 0;
    	}
    	shooterPositionTalon.set(power);
    }
    
    public boolean isShooterAtHome() {
    	return ! shooterHomeDigitalInput.get();
    	
    }
    
    
    public void initDefaultCommand() {

    	setDefaultCommand(new ShooterTiltCommand());

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

